
export const tv= [
    
        {
            "id": 1,
            "price": 35000.99,
            "name": "Samsung QLED 65-Inch",
            "description": "Stunning 4K UHD picture quality with Quantum Dot technology.",
            "category": "Televisions",
            "image": "https://rukminim2.flixcart.com/image/312/312/xif0q/television/k/h/w/-original-imah3868qdatnqg8.jpeg?q=70",
            "inStock": true,
            "discount": true,
             "stock": 10,

        },
        {
            "id": 2,
            "price": 40000.99,
            "name": "LG OLED 55-Inch",
            "description": "Self-lighting OLED technology for perfect blacks and vibrant colors.",
            "category": "Televisions",
            "image":"",
            "inStock": true,
            "discount": false,
             "stock": 3,
        },
        {
            "id": 3,
            "price": 4000.99,
            "name": "Sony LED 50-Inch",
            "description": "Full HD LED TV with advanced color reproduction and clarity.",
            "category": "Televisions",
            "image": "https://rukminim2.flixcart.com/image/312/312/xif0q/television/d/o/p/-original-imah4ndsahafgd9c.jpeg?q=70",
            "inStock": false,
            "discount": true,
             "stock": 0,
        },
        {
            "id": 4,
            "price": 15000.99,
            "name": "TCL 43-Inch Roku TV",
            "description": "Affordable Smart TV with built-in Roku for easy streaming.",
            "category": "Televisions",
            "image": "https://rukminim2.flixcart.com/image/312/312/xif0q/television/r/f/s/-original-imagvbmgfbsxerhz.jpeg?q=70",
            "inStock": true,
            "discount": false,
            "stock": 5,
        },
        {
            "id": 5,
            "price": 5000.99,
            "name": "Apple TV 4K 65-Inch",
            "description": "Ultimate Smart TV experience with stunning visuals and smart features.",
            "category": "Televisions",
            "image": "https://rukminim2.flixcart.com/image/312/312/xif0q/television/f/s/h/-original-imah54herepenkrb.jpeg?q=70",
            "inStock": true,
            "discount": true,
            "stock": 2,
        }
    ];
    

 export const fashion =
[
    {
        "id": 1,
        "name": "Classic Leather Jacket",
        "price": 3000.99,
        "description": "Timeless black leather jacket with a fitted silhouette.",
        "category": "Outerwear",
        "image":"https://rukminim2.flixcart.com/image/612/612/xif0q/jacket/v/3/l/l-1-no-trendy-black-pu-faux-leather-biker-jacket-for-men-moody-original-imah2spwwwyqjf3z.jpeg?q=70",
        "inStock": true,
        "discount": false,
        "stock": 15,
    },

    {
        "id": 2,
        "name": "Slim Fit Jeans",
        "price": 230.99,
        "description": "Stylish slim fit jeans made from premium denim for ultimate comfort.",
        "category": "Bottoms",
        "image":"", 
        "inStock": true,
         "discount": true,
        "stock": 8,       
    },
    {
        "id": 3,
        "name": "Cotton Graphic T-Shirt",
        "price": 101.99,
        "description": "Soft cotton t-shirt with a trendy graphic design.",
        "category": "Tops",
        "image":"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/x/n/e/m-90s-anime-oversize-tshirt-for-men-zen1fashion-original-imahyy4gevtgn6hz.jpeg?q=70",
        "inStock": true,
        "discount": false,
        "stock": 2,
    },
    {
        "id": 4,
        "name": "Chunky Knit Sweater",
        "price": 725.99,
        "description": "Cozy chunky knit sweater perfect for chilly days.",
        "category": "Knitwear",
        "image":"https://rukminim2.flixcart.com/image/612/612/xif0q/sweatshirt/e/d/b/9-10-years-itachi-anime-printed-swaetshirt-shree-chintransh-original-imaguyytkgkuyzug.jpeg?q=70",
        "inStock": true,
        "discount": true,
        "stock": 2,
    },
    {
        "id": 5,
        "name": "Classic Sneakers",
        "price": 569.19,
        "description": "Versatile and comfortable sneakers for everyday wear.",
        "category": "Footwear",
        "image":"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/o/m/p/7-itachi-7-dee-design-itachi-original-imah2cuhhj8cd7je.jpeg?q=70", 
        "inStock": true,
         "discount": true,
        "stock": 1,       
    }
]
export const airbuds =[
    
        {
            "id": 1,
            "name": "Apple AirPods Pro",
            "price": 10000.99,
            "description": "Active Noise Cancellation and Transparency mode for immersive sound.",
            "category": "Earbuds",
            "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/h/k/g/-original-imah4jvf79j6xdtd.jpeg?q=70",
            "inStock": true,
            "discount": true,
            "stock": 12,
        },
        {
            "id": 2,
            "name": "Samsung Galaxy Buds2",
            "price": 3000.29,
            "description": "Lightweight earbuds with rich sound and customizable fit.",
            "category": "Earbuds",
            "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/o/m/l/galaxy-buds2-pro-sm-r510nlvainu-new-samsung-original-imags7kfzhmvewh3.jpeg?q=70",
            "inStock": true,
            "discount": false,
             "stock": 1,
        },
        {
            "id": 3,
            "name": "Jabra Elite 75t",
            "price": 4000.99,
            "description": "Compact design with exceptional sound quality and battery life.",
            "category": "Earbuds",
            "image": "",
            "inStock": true,
            "discount": true,
            "stock": 2,
        },
        {
            "id": 4,
            "name": "Sony WF-1000XM4",
            "price": 5000.89,
            "description": "Industry-leading noise cancellation and superior sound quality.",
            "category": "Earbuds",
            "image": "https://rukminim2.flixcart.com/image/612/612/ky7lci80/headphone/h/d/p/wf-c500-dz-in-sony-original-imagahvzcymkzyma.jpeg?q=70",

        },
        {
            "id": 5,
            "name": "Anker Soundcore Life P2",
            "price": 2500.99,
            "description": "Affordable true wireless earbuds with impressive battery life.",
            "category": "Earbuds",
            "image": "https://rukminim2.flixcart.com/image/612/612/kkh6zrk0/headphone/y/v/o/liberty-air-2-pro-soundcore-original-imafzta7b8bhgnz5.jpeg?q=70",
            "inStock": true,
            "discount": false,
            "stock": 8,
        }
    ]
    

export const laptop =
[
    {
        "id": 1,
        "name": "Dell XPS 13",
        "price": 235.99,
        "description": "Compact and powerful ultrabook with a stunning InfinityEdge display.",
        "category": "Laptops",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/computer/l/h/1/inspiron-3520-thin-and-light-laptop-dell-original-imahyggypmfkkpnf.jpeg?q=70",
        "inStock": true,
        "discount": true,
        "stock": 6,
    },
    {
        "id": 2,
        "name": "Apple MacBook Air M2",
        "price": 780.99,
        "description": "Lightweight laptop with Apple's M2 chip for exceptional performance.",
        "category": "Laptops",
        "image": "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/2/v/v/-original-imagfdeqter4sj2j.jpeg?q=70",
        "inStock": true,
        "discount": false,
       "stock": 10,
    },
    {
        "id": 3,
        "name": "HP Spectre x360",
        "price": 850.99,
        "description": "2-in-1 convertible laptop with a sleek design and long battery life.",
        "category": "Laptops",
        "image": "",
        "inStock": true,
         "discount": true,
        "stock": 1,
    },
    {
        "id": 4,
        "name": "Lenovo ThinkPad X1 Carbon",
        "price": 500.99,
        "description": "Business-ready laptop with robust security features and excellent keyboard.",
        "category": "Laptops",
        "image": "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/t/r/u/-original-imah3acvkdhmxkzq.jpeg?q=70",
        "inStock": true,
        "discount": false,
        "stock": 2,
    },
    {
        "id": 5,
        "name": "ASUS ROG Zephyrus G14",
        "price": 609.99,
        "description": "High-performance gaming laptop with AMD Ryzen and NVIDIA graphics.",
        "category": "Laptops",
        "image": "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/3/2/s/-original-imah2ger8qjev3sj.jpeg?q=70",
        "inStock": true,
        "discount": false,
         "stock": 1,
    }
]
 export const mobiles =
[
    {
        "id": 1,
        "name": "Apple iPhone 14 Pro",
        "price": 700.00,
        "description": "Featuring a stunning Super Retina XDR display and A16 Bionic chip.",
        "category": "Mobile Phones",
        "image": "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/j/z/3/-original-imagtc5fqyz8tu4c.jpeg?q=70",
        "inStock": true,
         "discount": false,
        "stock": 2,
    },
    {
        "id": 2,
        "name": "Samsung Galaxy S23 Ultra",
        "price": 300.99,
        "description": "High-performance smartphone with a versatile camera system and S Pen.",
        "category": "Mobile Phones",
        "image": "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/u/a/l/-original-imagzm8qrfdmhy8z.jpeg?q=70",
        "inStock": true,
        "discount": false,
        "stock": 10,
    },
    {
        "id": 3,
        "name": "Google Pixel 7",
        "price": 859.99,
        "description": "Smartphone with exceptional camera capabilities and clean Android experience.",
        "category": "Mobile Phones",
        "image": "",
        "inStock": false,
        "discount": true,
        "stock": 0,
    },
    {
        "id": 4,
        "name": "OnePlus 11",
        "price": 200.99,
        "description": "Flagship smartphone with fast charging and smooth performance.",
        "category": "Mobile Phones",
        "image": "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/p/r/b/nord-ce-3-lite-5g-ce2099-oneplus-original-imagzj42cctpjjze.jpeg?q=70",
        "inStock": true,
        "discount": false,
         "stock": 3,
    },
    {
        "id": 5,
        "name": "Xiaomi 13 Pro",
        "price": 450.09,
        "description": "Innovative smartphone with Leica camera technology and powerful performance.",
        "category": "Mobile Phones",
        "image": "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/g/q/5/-original-imahfkf6jcuhhzyb.jpeg?q=70",
        "inStock": true,
        "discount": false,
        "stock": 3,
    }
]



